
trainer:
  checkpoint: "/content/drive/MyDrive/checkpoint/2spk_pit_psm_c"
  optimizer: "adam"
  #lr: 1.0e-4
  lr: 4.0e-6
  momentum: 0.9
  weight_decay: 0
  clip_norm: 200
  min_lr: 1.0e-10
  patience: 0
  factor: 0.7

model:
  num_spks: 2
  rnn: "lstm"
  num_layers: 3
  hidden_size: 896
  dropout: 0.5
  non_linear: "relu"
  bidirectional: true

spectrogram_reader:
  frame_shift: 128
  frame_length: 256
  window: "hann"
  transpose: true
  # NOTE: do not apply log here
  # false => produce psm
  # true  => produce irm
  apply_abs: false

train_scp_conf:
  mixture: "/content/uPIT-for-speech-separation/scp/tr_mx.scp"
  spk1: "/content/uPIT-for-speech-separation/scp/tr_s1.scp"
  spk2: "/content/uPIT-for-speech-separation/scp/tr_s2.scp"

valid_scp_conf:
  mixture: "/content/uPIT-for-speech-separation/scp/cv_mx.scp"
  spk1: "/content/uPIT-for-speech-separation/scp/cv_s1.scp"
  spk2: "/content/uPIT-for-speech-separation/scp/cv_s2.scp"

debug_scp_conf:
  mixture: "/content/uPIT-for-speech-separation/scp/tt_mx.scp"
  spk1: "/content/uPIT-for-speech-separation/scp/tt_s1.scp"
  spk2: "/content/uPIT-for-speech-separation/scp/tt_s2.scp"

dataloader:
  shuffle: true
  batch_size: 20
  drop_last: false
  mvn_dict: "/content/uPIT-for-speech-separation/cmvn.dict"
